# Generated by Django 2.2.5 on 2019-10-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhostPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
