# Generated by Django 2.2.5 on 2019-10-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhostPost', '0002_post_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='roast',
            field=models.BooleanField(default=False),
        ),
    ]
