# Generated by Django 2.2.5 on 2019-10-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GhostPost', '0003_auto_20191002_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='roast',
        ),
    ]
