# Generated by Django 2.2.5 on 2019-10-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GhostPost', '0004_remove_post_roast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='boast',
            field=models.BooleanField(default=False),
        ),
    ]
